groups:
- name: default
  rules:

  # Alert for any instance that is unreachable for > 2 minutes.
  - alert: service_down
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

  - alert: high_load
    expr: system_cpu_usage > 0.8
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} is under high load"
      description: "{{ $labels.instance }} has an average CPU idle (current value: {{ $value }}s)."